feat: can add existing point (map location) to your route
Apes2getherStrong/WayToGo-FrontEnd pull request #101
Opened 2024-07-31 08:37 UTC by Kondziow

No ogolnie chyba dziala. Sposob Oskara, czyli z poziomu szczegolow trasy mozemy dodac punkt do naszej trasy.

Jak macie chwile to potestujcie czy nie ma bugow zadnych

2024-08-17 06:42 UTC, Janek1010 approved these changes

2024-08-22 18:11 UTC, Drillllll commented
Kondzio popraw responsywność pliska
![image](https://github.com/user-attachments/assets/425231c4-871e-432b-94f8-3fb326b620c4)

2024-08-22 18:14 UTC, Drillllll requested changes
layout do poprawy

2024-08-26 11:21 UTC, Drillllll requested changes

2024-08-26 11:21 UTC, Drillllll commented on src/app/route-map-location/route-map-location.service.ts
> +          return of(null); // Zwraca Observable z wartością `null`, gdy rekord już istnieje
change the comment to eng

2024-08-26 11:21 UTC, Drillllll commented on src/app/route/route-list/route-list.component.ts
> +  @Input() addingPointToRouteId: string;
I would change the name. It's vague. I don't know if it refers to ML id or route id. 
maby "pointIdToBeAdded(toRoute)" ?

2024-08-26 11:21 UTC, Drillllll commented on src/app/route/route-list/route-list.component.ts
> +          this.router.navigate(['../list'], {relativeTo: this.activatedRoute})
investigate the redirect

2024-08-26 11:36 UTC, Drillllll commented
Additionally the code in list is becoming a spaghetti with every task. What do you think about the structure like that?

![image](https://github.com/user-attachments/assets/9f91c951-07fb-4ec5-b2d1-4bc5db0ddae4)

2024-08-26 11:37 UTC, Drillllll commented
by stealingML I mean adding ML to my route. It's shorter this way

2024-08-26 11:38 UTC, Drillllll commented
This isn't a change request, but just my personal opinion. Just want to ask what u think

2024-08-26 11:51 UTC, Kondziow commented
It seems to be a good idea but I think it requires a new task. It can be complex.

2024-08-26 13:15 UTC, Drillllll approved these changes

2024-08-26 13:56 UTC, merged