80 audio w edycji map location w edycji routa
Apes2getherStrong/WayToGo-FrontEnd pull request #95
Opened 2024-06-24 14:35 UTC by niksuu

80 audio w edycji map location w edycji routa

2024-06-29 06:32 UTC, Janek1010 approved these changes

2024-07-02 19:50 UTC, Drillllll requested changes
Kilka rzeczy do poprawy:
- Tak jak pisałem wcześniej, przy dodawaniu nowego map location powinna być możliwość dodania audiosów (obecnie nie ma)
- dziwne jest to że trzeba zapisać edycję map location żeby zapisać nowe audio. Nie ma to sensu. Pod listą powino być pole na nazwę i plik audio nowego audio i przycisk dodania, który zatwierdza dodanie audio ale nie zamyka strony edycji map location. 
- Na ten moment audio description nie jest nigdzie wyświetlane (zrezygnowaliśmy z tego) więc można je wyrzucić z edycji 
- Ta nowa strona na edycję audio jest niepotrzebna. Tak jak Ci pisałem wcześniej: "na ten moment chyba najlepiej bedzie po prostu do komponentu map location edit dodac liste audios (pliki mp3 z możliwością odtworzenia i nazwą - tak jak jest w map location list, obok każdego audio dodatkowo przycisk na usunięcie go z listy) z opcją dodania nowego audio".  Poniżej sugestia jak lepiej to zrobić

![image](https://github.com/Apes2getherStrong/WayToGo-FrontEnd/assets/118617644/0d66035b-9496-43d0-a194-5ef53121c5be)

2024-09-03 17:09 UTC, Drillllll approved these changes

2024-09-03 19:08 UTC, Janek1010 approved these changes

2024-09-03 19:08 UTC, merged